interfaces = []
exclude = [
    ".*__pycache__",
    ".*egg-info",
    "docs",
    "tests",
]
source_roots = [
    ".",
]

[[modules]]
path = "<root>"
depends_on = [
    "ee",
    "posthog",
]

[[modules]]
path = "common.hogql_parser"
depends_on = []

[[modules]]
path = "common.hogvm.python"
depends_on = [
    "posthog",
]

[[modules]]
path = "ee"
depends_on = [
    "common.hogvm.python",
    "posthog",
]

[[modules]]
path = "posthog"
depends_on = [
    "<root>",
    "common.hogvm.python",
    "ee",
    "products.early_access_features",
    "products.links",
    "products.revenue_analytics",
]

[[modules]]
path = "products.early_access_features"
depends_on = [
    "posthog",
]

[[modules]]
path = "products.links"
depends_on = [
    "posthog",
]

[[modules]]
path = "products.revenue_analytics"
depends_on = [
    "posthog",
]
